// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "/home/cesco/youtube/fltk/fluid_tut2/src/src/CFluidWindow.h"

CFluidWindow::CFluidWindow() {
  { win_app = new Fl_Double_Window(725, 590, "Image Window");
    win_app->user_data((void*)(this));
    { box_jpeg_image = new Fl_Box(25, 25, 680, 476, "Image Box");
    } // Fl_Box* box_jpeg_image
    { btn_show_jpeg = new Fl_Button(295, 520, 160, 40, "Click to show Image");
    } // Fl_Button* btn_show_jpeg
    win_app->end();
  } // Fl_Double_Window* win_app
}
