/ generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef CFluidWindow_h
#define CFluidWindow_h
#include <FL/Fl.H>
#include <iostream>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>

class CFluidWindow {
public:
  CFluidWindow();
  Fl_Double_Window *win_app;
  Fl_Box *box_jpeg_image;
  Fl_Button *btn_show_jpeg;
};
#endif
